; YoMama E22P board variant - DIY
[env:yomama_e22p]
custom_meshtastic_hw_model = PRIVATE_HW
custom_meshtastic_hw_model_slug = YOMAMA_E22P
custom_meshtastic_architecture = nrf52840
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = YoMama E22P
custom_meshtastic_tags = DIY
custom_meshtastic_requires_dfu = true

extends = nrf52840_base
board = promicro-nrf52840

build_flags =
    ${nrf52840_base.build_flags}
    -I variants/nrf52840/diy/yomama_e22p
    -D PRIVATE_HW
    -D YOMAMA_E22P

build_src_filter =
    ${nrf52_base.build_src_filter}
    +<../variants/nrf52840/diy/yomama_e22p>

debug_tool = jlink
