; YoMama E22P board variant - DIY
[env:yomama_e22p]
custom_meshtastic_hw_model = PRIVATE_HW
custom_meshtastic_hw_model_slug = YOMAMA_E22P
custom_meshtastic_architecture = nrf52840
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = YoMama E22P
custom_meshtastic_tags = DIY
custom_meshtastic_requires_dfu = true

extends = nrf52840_base
board = promicro-nrf52840

build_flags =
    ${nrf52840_base.build_flags}
    -I variants/nrf52840/diy/yomama_e22p
    -D PRIVATE_HW
    -D YOMAMA_E22P

build_src_filter =
    ${nrf52_base.build_src_filter}
    +<../variants/nrf52840/diy/yomama_e22p>

debug_tool = jlink

[env:yomama_e22p_nogps]
extends = env:yomama_e22p

build_flags =
    ${env:yomama_e22p.build_flags}
    -DMESHTASTIC_EXCLUDE_GPS=1
    -DYOMAMA_E22P_DISABLE_GPS=1

lib_ignore =
    TinyGPSPlus

[env:yomama_e22p_minradio]
extends = env:yomama_e22p_nogps

build_flags =
    ${env:yomama_e22p_nogps.build_flags}
    -DMESHTASTIC_MINIMIZE_BUILD=1
    -DMESHTASTIC_EXCLUDE_I2C=1
    -DMESHTASTIC_EXCLUDE_SCREEN=1
    -DMESHTASTIC_EXCLUDE_BLUETOOTH=1

lib_ignore =
    ${env:yomama_e22p_nogps.lib_ignore}
    ESP8266 and ESP32 OLED driver for SSD1306 displays
    Adafruit SH110X
    Adafruit GFX Library
    Adafruit SSD1306
    Adafruit BMP280 Library
    Adafruit BMP085 Library
    Adafruit BME280 Library
    Adafruit DPS310
    Adafruit MCP9808 Library
    Adafruit INA260 Library
    Adafruit INA219
    Adafruit MPU6050
    Adafruit LIS3DH
    Adafruit AHTX0
    Adafruit LSM6DS
    Adafruit TSL2591 Library
    EmotiBit MLX90632
    Adafruit MLX90614 Library
    INA3221
    QMC5883LCompass
    DFRobot_RTU
    DFRobot_RainfallSensor
    INA226
    SparkFun MAX3010x Pulse and Proximity Sensor Library
    SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library
    Adafruit LTR390 Library
    Adafruit PCT2075
    DFRobot_BMM150
    Adafruit TSL2561
    BH1750_WE
    Adafruit BMP3XX Library
    Adafruit MAX1704X
    Adafruit SHTC3 Library
    Adafruit LPS2X
    Adafruit SHT31 Library
    Adafruit VEML7700 Library
    Adafruit SHT4x Library
    SparkFun Qwiic Scale NAU7802 Arduino Library
    ClosedCube OPT3001
    DFRobot_LarkWeatherStation
    Sensirion Core
    Sensirion I2C SCD4x
    Sensirion I2C SFA3x
    Sensirion I2C SCD30
    arduino-sht
    bsec2
    BME68x Sensor library

[env:yomama_e22p_minradio_strict]
extends = env:yomama_e22p_minradio

build_src_filter =
    ${env:yomama_e22p.build_src_filter}
    -<gps/>
    -<graphics/>
    -<input/>
    -<detect/>
    -<motion/>
    -<buzz/>
    +<gps/RTC.cpp>
    +<detect/ScanI2C.cpp>
    +<buzz/buzz.cpp>

lib_deps =
    # renovate: datasource=git-refs depName=meshtastic-esp8266-oled-ssd1306 packageName=https://github.com/meshtastic/esp8266-oled-ssd1306 gitBranch=master
    https://github.com/meshtastic/esp8266-oled-ssd1306/archive/21e484f409cde18d44012caef84c244eb5ca28f3.zip
    # renovate: datasource=git-refs depName=meshtastic-arduino-fsm packageName=https://github.com/meshtastic/arduino-fsm gitBranch=master
    https://github.com/meshtastic/arduino-fsm/archive/7db3702bf0cfe97b783d6c72595e3f38e0b19159.zip
    # renovate: datasource=git-refs depName=meshtastic-ArduinoThread packageName=https://github.com/meshtastic/ArduinoThread gitBranch=master
    https://github.com/meshtastic/ArduinoThread/archive/b841b0415721f1341ea41cccfb4adccfaf951567.zip
    # renovate: datasource=github-tags depName=Nanopb packageName=nanopb/nanopb
    https://github.com/nanopb/nanopb/archive/refs/tags/nanopb-0.4.9.1.zip
    # renovate: datasource=github-tags depName=ErriezCRC32 packageName=Erriez/ErriezCRC32
    https://github.com/Erriez/ErriezCRC32/archive/refs/tags/1.0.1.zip
    # renovate: datasource=github-tags depName=NonBlockingRTTTL packageName=end2endzone/NonBlockingRTTTL
    https://github.com/end2endzone/NonBlockingRTTTL/archive/refs/tags/1.4.0.zip
    # renovate: datasource=github-tags depName=RadioLib packageName=jgromes/RadioLib
    https://github.com/jgromes/RadioLib/archive/refs/tags/7.6.0.zip
    # renovate: datasource=custom.pio depName=rweather/Crypto packageName=rweather/library/Crypto
    rweather/Crypto@0.4.0
    # renovate: datasource=git-refs depName=Kongduino-Adafruit_nRFCrypto packageName=https://github.com/Kongduino/Adafruit_nRFCrypto gitBranch=master
    https://github.com/Kongduino/Adafruit_nRFCrypto/archive/8cde7189b5ead9dcd49f72601b43b969c0bbc06e.zip

lib_ignore =
    TinyGPSPlus
    Adafruit SH110X
    Adafruit GFX Library
    Adafruit SSD1306
    Adafruit BMP280 Library
    Adafruit BMP085 Library
    Adafruit BME280 Library
    Adafruit DPS310
    Adafruit MCP9808 Library
    Adafruit INA260 Library
    Adafruit INA219
    Adafruit MPU6050
    Adafruit LIS3DH
    Adafruit AHTX0
    Adafruit LSM6DS
    Adafruit TSL2591 Library
    EmotiBit MLX90632
    Adafruit MLX90614 Library
    INA3221
    QMC5883LCompass
    DFRobot_RTU
    DFRobot_RainfallSensor
    INA226
    SparkFun MAX3010x Pulse and Proximity Sensor Library
    SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library
    Adafruit LTR390 Library
    Adafruit PCT2075
    DFRobot_BMM150
    Adafruit TSL2561
    BH1750_WE
    Adafruit BMP3XX Library
    Adafruit MAX1704X
    Adafruit SHTC3 Library
    Adafruit LPS2X
    Adafruit SHT31 Library
    Adafruit VEML7700 Library
    Adafruit SHT4x Library
    SparkFun Qwiic Scale NAU7802 Arduino Library
    ClosedCube OPT3001
    DFRobot_LarkWeatherStation
    Sensirion Core
    Sensirion I2C SCD4x
    Sensirion I2C SFA3x
    Sensirion I2C SCD30
    arduino-sht
    bsec2
    BME68x Sensor library

[env:yomama_e22p_bare]
extends = env:yomama_e22p_nogps

build_flags =
    ${env:yomama_e22p_nogps.build_flags}
    -DMESHTASTIC_EXCLUDE_SCREEN=1
    -DYOMAMA_E22P_BARE_FORCE_BLE=1
    -DMESHTASTIC_EXCLUDE_MQTT=1
    -DMESHTASTIC_EXCLUDE_POWERMON=1
    -DMESHTASTIC_EXCLUDE_PKI=1
    -DMESHTASTIC_EXCLUDE_POWER_FSM=1
    -DMESHTASTIC_EXCLUDE_TZ=1
    -DMESHTASTIC_EXCLUDE_REMOTEHARDWARE=1
    -DMESHTASTIC_EXCLUDE_STOREFORWARD=1
    -DMESHTASTIC_EXCLUDE_TRAFFIC_MANAGEMENT=1
    -DMESHTASTIC_EXCLUDE_ATAK=1
    -DMESHTASTIC_EXCLUDE_CANNEDMESSAGES=1
    -DMESHTASTIC_EXCLUDE_NEIGHBORINFO=1
    -DMESHTASTIC_EXCLUDE_TRACEROUTE=1
    -DMESHTASTIC_EXCLUDE_WAYPOINT=1
    -DMESHTASTIC_EXCLUDE_INPUTBROKER=1
    -DMESHTASTIC_EXCLUDE_SERIAL=1
    -DMESHTASTIC_EXCLUDE_POWERSTRESS=1
    -DMESHTASTIC_EXCLUDE_EXTERNALNOTIFICATION=1
    -DMESHTASTIC_EXCLUDE_DETECTIONSENSOR=1
    -DMESHTASTIC_EXCLUDE_ACCELEROMETER=1
    -DMESHTASTIC_EXCLUDE_AIR_QUALITY_SENSOR=1
    -DMESHTASTIC_EXCLUDE_HEALTH_TELEMETRY=1

build_src_filter =
    ${env:yomama_e22p.build_src_filter}
    -<gps/>
    -<graphics/>
    -<input/>
    -<detect/>
    -<motion/>
    -<buzz/>
    -<mqtt/>
    -<modules/>
    -<modules/Telemetry/>
    -<platform/nrf52/AsyncUDP.cpp>
    -<platform/extra_variants/>
    +<gps/RTC.cpp>
    +<detect/ScanI2C.cpp>
    +<detect/ScanI2CConsumer.cpp>
    +<detect/ScanI2CTwoWire.cpp>
    +<buzz/buzz.cpp>
    +<modules/Modules.cpp>
    +<modules/AdminModule.cpp>
    +<modules/NeighborInfoModule.cpp>
    +<modules/NodeInfoModule.cpp>
    +<modules/RoutingModule.cpp>
    +<modules/SerialModule.cpp>
    +<modules/StatusLEDModule.cpp>
    +<modules/Telemetry/PowerTelemetry.cpp>
    +<modules/Telemetry/EnvironmentTelemetry.cpp>
    +<modules/Telemetry/UnitConversions.cpp>
    +<modules/Telemetry/Sensor/TelemetrySensor.cpp>
    +<modules/Telemetry/Sensor/nullSensor.cpp>
    +<modules/Telemetry/Sensor/INA219Sensor.cpp>
    +<modules/Telemetry/Sensor/INA226Sensor.cpp>
    +<modules/Telemetry/Sensor/INA260Sensor.cpp>
    +<modules/Telemetry/Sensor/INA3221Sensor.cpp>
    +<modules/Telemetry/Sensor/RCWL9620Sensor.cpp>
    +<modules/Telemetry/Sensor/CGRadSensSensor.cpp>
    +<modules/TextMessageModule.cpp>
    +<modules/Telemetry/DeviceTelemetry.cpp>

lib_deps =
    ${env:yomama_e22p_minradio_strict.lib_deps}
    adafruit/Adafruit INA260 Library@1.5.3
    adafruit/Adafruit INA219@1.2.3
    robtillaart/INA226@0.6.6
    https://github.com/sgtwilko/INA3221/archive/bb03d7e9bfcc74fc798838a54f4f99738f29fc6a.zip

lib_ignore =
    TinyGPSPlus
    Adafruit SH110X
    Adafruit GFX Library
    Adafruit SSD1306
    Adafruit BMP280 Library
    Adafruit BMP085 Library
    Adafruit BME280 Library
    Adafruit DPS310
    Adafruit MCP9808 Library
    Adafruit MPU6050
    Adafruit LIS3DH
    Adafruit AHTX0
    Adafruit LSM6DS
    Adafruit TSL2591 Library
    EmotiBit MLX90632
    Adafruit MLX90614 Library
    QMC5883LCompass
    DFRobot_RTU
    DFRobot_RainfallSensor
    SparkFun MAX3010x Pulse and Proximity Sensor Library
    SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library
    Adafruit LTR390 Library
    Adafruit PCT2075
    DFRobot_BMM150
    Adafruit TSL2561
    BH1750_WE
    Adafruit BMP3XX Library
    Adafruit MAX1704X
    Adafruit SHTC3 Library
    Adafruit LPS2X
    Adafruit SHT31 Library
    Adafruit VEML7700 Library
    Adafruit SHT4x Library
    SparkFun Qwiic Scale NAU7802 Arduino Library
    ClosedCube OPT3001
    DFRobot_LarkWeatherStation
    Sensirion Core
    Sensirion I2C SCD4x
    Sensirion I2C SFA3x
    Sensirion I2C SCD30
    arduino-sht
    bsec2
    BME68x Sensor library
