; Liberty MeshMess + nRF52840 Pro Micro + E22P/E22 SX1262 module - DIY
[env:liberty_meshmess_e22p]
custom_meshtastic_hw_model = PRIVATE_HW
custom_meshtastic_hw_model_slug = LIBERTY_MESHMESS_E22P
custom_meshtastic_architecture = nrf52840
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = Liberty MeshMess E22P
custom_meshtastic_tags = DIY
custom_meshtastic_requires_dfu = true

extends = nrf52840_base
board = promicro-nrf52840

build_flags =
    ${nrf52840_base.build_flags}
    -I variants/nrf52840/diy/liberty_meshmess_e22p
    -D PRIVATE_HW
    -D LIBERTY_MESHMESS_E22P
    -DMESHTASTIC_EXCLUDE_GPS=1
    -DMESHTASTIC_EXCLUDE_SCREEN=1
    -DMESHTASTIC_EXCLUDE_ACCELEROMETER=1
    -DMESHTASTIC_EXCLUDE_INPUTBROKER=1

build_src_filter =
    ${nrf52_base.build_src_filter}
    -<gps/>
    -<graphics/>
    -<input/>
    -<motion/>
    +<gps/RTC.cpp>
    +<gps/GeoCoord.cpp>
    +<../variants/nrf52840/diy/liberty_meshmess_e22p>

debug_tool = jlink
